language: node_js
os: linux
node_js:
  - 14

stages:
  - build
  - linter
  - unit tests
  - deploy

jobs:
  include:
    - stage: build
      name: Build da aplicação JavaScript
      script: npm install

